# Generated by Django 3.0.4 on 2020-07-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.TextField(max_length=12)),
                ('address', models.TextField(max_length=200)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oxygen_saturation', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
