# Generated by Django 3.0.7 on 2020-07-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200724_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('Aadhar', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SpO2', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
