# Generated by Django 3.0.7 on 2020-07-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200731_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Aadhar',
            field=models.BigIntegerField(),
        ),
    ]
